name: C to Flowchart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  convert:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Visustin
        run: |
          # Download and install Visustin from https://www.aivosto.com/visustin.html
          # You may need a license key to activate the software
      - name: Convert C files to flowcharts
        run: |
          # Run Visustin with command line options to convert code/*.c files to flowchart/*.svg files
          # For example: visustin -svg -out=flowchart code/*.c
          # See https://www.aivosto.com/visustin/help/en/commandline.html for more details
      - name: Upload flowcharts
        uses: actions/upload-artifact@v2
        with:
          name: flowcharts
          path: flowchart
